# Generated by Django 5.0.2 on 2024-09-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_language_remove_ebookmodel_likes_ebookmodel_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookmodel',
            name='store',
            field=models.URLField(blank=True, null=True),
        ),
    ]
