# Generated by Django 5.0.2 on 2024-11-07 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ebookmodel_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ebookmodel')),
            ],
            options={
                'verbose_name_plural': 'Downloads',
            },
        ),
        migrations.CreateModel(
            name='PageViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, null=True)),
                ('creat', models.DateTimeField(auto_now_add=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ebookmodel')),
            ],
            options={
                'verbose_name_plural': 'Page Views',
            },
        ),
    ]
