# Generated by Django 5.0.2 on 2024-11-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_downloadcount_pageviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageviews',
            old_name='creat',
            new_name='created_on',
        ),
    ]
